version: "3"
services:
 grafana:
  #build: .
  image: grafana/grafana:5.1.0
  container_name: grafana
  environment:
   - GF_SERVER_ROOT_URL=http://192.168.99.101:3000
   - GF_SECURITY_ADMIN_PASSWORD=123456
   - TS="America/Bahia"
  #volumes:
  #	- grafana-storage:/var/lib/grafana
  ports:
   - 3000:3000
  user: "104"
  
mysql:
 container_name: mysqlcontainer
 image: mysql:5.7
 ports: 
      - 3306:3306
 environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fiapdb
      MYSQL_USER: fiap
      MYSQL_PASSWORD: 123456
      TZ: "America/Bahia"
